{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llmops.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llmops.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}

